version: "3.9"
services:
  shopping-list:
    container_name: shopping-list
    image: beschoenen/shopping-list:latest
    restart: unless-stopped
    networks:
      - shopping-list
    ports:
      - "${PORT:-80}:80"
    environment:
      PORT: "80"
      MONGO_HOST: "shopping-list-db"
      MONGO_DB: "shopping-list"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
  mongodb:
    container_name: shopping-list-db
    image: mongo:4
    restart: unless-stopped
    networks:
      - shopping-list
    volumes:
      - "./database:/data/db"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
networks:
  shopping-list:
    name: shopping-list
    driver: bridge
